services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app      
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - REDIS_URL=redis://redis:6379
      - GRAPHQL_ENABLED=false
    depends_on:
      - db
      - redis
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: